[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "GPL-2.0-only",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "WTFPL",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
